wsl install scripts

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,8 +1,53 @@
-echo "
-.____    .___  ______________________________
-|    |   |   |/   _____/\____    /\__    ___/
-|    |   |   |\_____  \   /     /   |    |   
-|    |___|   |/        \ /     /_   |    |   
-|_______ \___/_______  //_______ \  |____|   
-        \/           \/         \/           
-"
+#!/usr/bin/env bash
+
+# $HOME/.config
+# $HOME/dev
+# $HOME/personal
+# $HOME/scripts
+
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+cd $SCRIPT_DIR
+
+DRY="0"
+
+TARGET=""
+
+LOG="INFO" #[OFF|ERROR|SUCCESS|INFO|DEBUG]
+
+while [[ $# > 0 ]]; do
+    case $1 in
+	-h | --help)
+	    source ./lizst_help
+	    exit 0
+	;;
+	-d | --dry) DRY=true;;
+	-t | --target) TARGET=$2; shift;;
+	--list-packages)
+	    echo "Not implemented"
+	    exit 0
+	;;
+	-l | --log) LOG=$2; shift;;
+	--os)
+	    echo "Not implemented"
+	    exit 0
+	;;
+	*)
+	    echo "Invalid argument: ${1}"
+	    echo "Usage: $0 [OPTIONS]"
+	    exit 1
+	;;
+    esac
+    shift
+done
+
+source ./logger $DRY $LOG
+
+log "DEBUG" "SCRIPT_DIR: ${SCRIPT_DIR}"
+log "DEBUG" "DRY: $DRY"
+log "DEBUG" "TARGET: $TARGET"
+log "DEBUG" "LOG: $LOG"
+
+OS="wsl"
+if [[ $OS == "wsl" ]]; then
+    source ./wsl/wsl-run
+fi
